"""empty message

Revision ID: 5c6ea56855b4
Revises: 4a0286b530db
Create Date: 2020-02-21 19:37:34.869937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6ea56855b4'
down_revision = '4a0286b530db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='show_pkey')
    )
    # ### end Alembic commands ###
