"""empty message

Revision ID: 650aa3a70691
Revises: 95323ebb0e5b
Create Date: 2020-02-21 23:13:05.335887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650aa3a70691'
down_revision = '95323ebb0e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
