"""empty message

Revision ID: 66b30cb0c4e3
Revises: 7b7ae10e09b7
Create Date: 2020-02-21 20:44:42.225002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66b30cb0c4e3'
down_revision = '7b7ae10e09b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venueId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artistId'], ['Artist.id'], name='Show_artistId_fkey'),
    sa.ForeignKeyConstraint(['venueId'], ['Venue.id'], name='Show_venueId_fkey'),
    sa.PrimaryKeyConstraint('artistId', 'venueId', name='Show_pkey')
    )
    # ### end Alembic commands ###
