"""empty message

Revision ID: 9dd861b48c03
Revises: 66b30cb0c4e3
Create Date: 2020-02-21 20:59:38.164951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd861b48c03'
down_revision = '66b30cb0c4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistId', sa.Integer(), nullable=False),
    sa.Column('venueId', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artistId'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venueId'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id', 'artistId', 'venueId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
