"""empty message

Revision ID: aad1f19177ef
Revises: 62171e85b833
Create Date: 2020-02-15 21:44:42.097609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad1f19177ef'
down_revision = '62171e85b833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('venue_name', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('artist_image_link', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
